import type {
  ActivityFeedItem,
  AgentRecord,
  ApprovalItem,
  ArchiveRecord,
  ContactCard,
  HelpResource,
  HomeUsageOverview,
  InboxThread,
  IntelligenceRecord,
  MeetingRecord,
  NavigationItem,
  PinnedItem,
  ProjectRecord,
  QuickConnection,
  RecentItem,
  RouteMeta,
  SettingsSection,
  SignalItem,
  StarterAction,
  UnifiedTask,
  WorkbenchTab,
  WorkflowDefinition,
  WorkflowRun,
} from "@/lib/ubik-types";

export const routeMetas: RouteMeta[] = [
  {
    key: "home",
    title: "Home",
    path: "/home",
    description: "Daily operating brief with compact usage intelligence and linked execution signals.",
    actions: [{ label: "Refresh", kind: "secondary" }],
    search: {
      placeholder: "Search home intelligence, activity, and follow-through",
      sections: ["Usage", "Activity", "Tasks"],
    },
  },
  {
    key: "chat",
    title: "Know Anything",
    path: "/",
    description: "Ask across organization knowledge, inbox, meetings, projects, chats, and linked work.",
    actions: [{ label: "New Thread", kind: "primary" }, { label: "Share", kind: "secondary" }],
    search: {
      placeholder: "Search chat history, artifacts, and starter prompts",
      sections: ["History", "Artifacts", "Prompts"],
    },
  },
  {
    key: "inbox",
    title: "Inbox",
    path: "/inbox",
    description: "Unified thread intelligence across inbound channels and extracted tasks.",
    actions: [{ label: "Sort", kind: "secondary" }, { label: "Filter", kind: "secondary" }],
    search: {
      placeholder: "Search threads, inbox artifacts, and action prompts",
      sections: ["Threads", "Artifacts", "Prompts"],
    },
  },
  {
    key: "tasks",
    title: "Tasks",
    path: "/tasks",
    description: "AI-routed follow-through across meetings, inbox, approvals, and workflow coverage.",
    actions: [{ label: "New Task", kind: "primary" }, { label: "Filter", kind: "secondary" }],
    search: {
      placeholder: "Search tasks, projects, assignees, and linked context",
      sections: ["Tasks", "Projects", "Context"],
    },
  },
  {
    key: "meetings",
    title: "Meetings",
    path: "/meetings",
    description: "Meeting continuity, decisions, and follow-through.",
    actions: [{ label: "Schedule", kind: "primary" }, { label: "Prep", kind: "secondary" }],
    search: {
      placeholder: "Search meeting history, files, and people",
      sections: ["History", "Artifacts", "People"],
    },
  },
  {
    key: "projects",
    title: "Projects",
    path: "/projects",
    description: "Operational workstreams connected to people, files, and approvals.",
    actions: [{ label: "New Project", kind: "primary" }, { label: "Review", kind: "secondary" }],
    search: {
      placeholder: "Search projects, linked artifacts, and next actions",
      sections: ["Projects", "Artifacts", "Next actions"],
    },
  },
  {
    key: "intelligence",
    title: "Intelligence",
    path: "/intelligence",
    description: "Research, monitoring, policy watch, and saved briefings.",
    actions: [{ label: "Research", kind: "primary" }, { label: "Monitor", kind: "secondary" }],
    search: {
      placeholder: "Search briefs, monitors, and saved research",
      sections: ["Actions", "Notes"],
    },
  },
  {
    key: "approvals",
    title: "Approvals",
    path: "/approvals",
    description: "Human-in-the-loop review queue with auditable recommendations.",
    actions: [{ label: "Review", kind: "primary" }, { label: "Filter", kind: "secondary" }],
    search: {
      placeholder: "Search approval packets and review actions",
      sections: ["Actions", "Notes"],
    },
  },
  {
    key: "workflows",
    title: "Workflows",
    path: "/workflows",
    description: "Deployable playbooks with runs, schedules, and queue visibility.",
    actions: [{ label: "New Workflow", kind: "primary" }, { label: "Queue", kind: "secondary" }],
    search: {
      placeholder: "Search workflows, runs, and queue actions",
      sections: ["Actions", "Notes"],
    },
  },
  {
    key: "agents",
    title: "Agents",
    path: "/agents",
    description: "Specialist agents monitored for health, outcomes, and approval mode.",
    actions: [{ label: "New Agent", kind: "primary" }, { label: "Inspect", kind: "secondary" }],
    search: {
      placeholder: "Search agent tasks, health, and inspections",
      sections: ["Actions", "Notes"],
    },
  },
  {
    key: "archive",
    title: "Archive",
    path: "/archive",
    description: "Historical records, completed runs, and prior conversations.",
    actions: [{ label: "Browse", kind: "secondary" }],
    search: {
      placeholder: "Search archived records and past conversations",
      sections: ["Actions", "Notes"],
    },
  },
  {
    key: "settings",
    title: "Settings",
    path: "/settings",
    description: "Workspace preferences, connectors, and environment details.",
    actions: [{ label: "Preferences", kind: "secondary" }],
    search: {
      placeholder: "Search preferences, connectors, and runtime details",
      sections: ["Actions", "Notes"],
    },
  },
  {
    key: "help",
    title: "Help",
    path: "/help",
    description: "Operator guides, escalation paths, and implementation notes.",
    actions: [{ label: "Support", kind: "secondary" }],
    search: {
      placeholder: "Search guides, escalation notes, and support actions",
      sections: ["Actions", "Notes"],
    },
  },
];

export const navigationItems: NavigationItem[] = [
  { key: "home", title: "Home", path: "/home", section: "navigate" },
  { key: "chat", title: "Know Anything", path: "/", section: "navigate" },
  { key: "inbox", title: "Inbox", path: "/inbox", section: "navigate", badge: "12" },
  { key: "tasks", title: "Tasks", path: "/tasks", section: "navigate", badge: "5" },
  { key: "meetings", title: "Meetings", path: "/meetings", section: "navigate" },
  { key: "projects", title: "Projects", path: "/projects", section: "navigate" },
  { key: "intelligence", title: "Intelligence", path: "/intelligence", section: "navigate", status: "watching" },
  { key: "approvals", title: "Approvals", path: "/approvals", section: "navigate", badge: "4", status: "urgent" },
  { key: "workflows", title: "Workflows", path: "/workflows", section: "playbooks", status: "live" },
  { key: "agents", title: "Agents", path: "/agents", section: "playbooks", status: "healthy" },
  { key: "archive", title: "Archive", path: "/archive", section: "support" },
  { key: "settings", title: "Settings", path: "/settings", section: "support" },
  { key: "help", title: "Help", path: "/help", section: "support" },
];

export const initialWorkbenchTabs: WorkbenchTab[] = [
  { id: "chat-home", routeKey: "chat", title: "Know Anything", path: "/", pinned: true, closable: false },
  { id: "inbox-main", routeKey: "inbox", title: "Inbox", path: "/inbox", pinned: true, closable: true },
  { id: "meetings-main", routeKey: "meetings", title: "Meetings", path: "/meetings", pinned: true, closable: true },
  { id: "projects-main", routeKey: "projects", title: "Projects", path: "/projects", pinned: true, closable: true },
];

export const workbenchLauncherRoutes = routeMetas.filter((route) =>
  ["/home", "/", "/inbox", "/tasks", "/meetings", "/projects", "/intelligence", "/approvals"].includes(route.path),
);

export const pinnedItems: PinnedItem[] = [
  { id: "pin-1", title: "Rate confirmation response", type: "chat", subtitle: "Awaiting legal sign-off" },
  { id: "pin-2", title: "Mumbai-Rotterdam Q2", type: "project", subtitle: "18 days remaining" },
  { id: "pin-3", title: "Daily pricing workflow", type: "workflow", subtitle: "Runs at 06:00 UTC" },
  { id: "pin-4", title: "Thai Union exception", type: "approval", subtitle: "Urgent review" },
  { id: "pin-5", title: "Supplier review sync", type: "meeting", subtitle: "Today · 10:30 AM" },
];

export const recentItems: RecentItem[] = [
  { id: "recent-1", title: "Thai Union response draft", type: "chat", time: "12 min ago" },
  { id: "recent-2", title: "Supplier review sync", type: "meeting", time: "34 min ago" },
  { id: "recent-3", title: "Pricing monitor run 842", type: "workflow", time: "1 hr ago" },
  { id: "recent-4", title: "Atlantic Fresh Q3", type: "project", time: "2 hrs ago" },
  { id: "recent-5", title: "Container handoff note", type: "file", time: "Today" },
  { id: "recent-6", title: "Morning operator brief", type: "chat", time: "Yesterday" },
];

export const quickConnections: QuickConnection[] = [
  { id: "gmail", label: "Gmail", state: "connected" },
  { id: "slack", label: "Slack", state: "connected" },
  { id: "whatsapp", label: "WhatsApp", state: "connected" },
  { id: "erp", label: "ERP", state: "watching" },
  { id: "crm", label: "CRM", state: "connected" },
  { id: "drive", label: "Drive", state: "connected" },
  { id: "calendar", label: "Calendar", state: "connected" },
];

export const starterActions: StarterAction[] = [
  {
    id: "start-1",
    title: "Carry a project forward",
    description: "Pull linked threads, files, workflows, and next actions before drafting an update.",
    category: "Project continuity",
    icon: "project",
    seedPrompt:
      "Continue the Mumbai-Rotterdam Q2 workstream. Pull the latest linked threads, approvals, and workflow artifacts, then tell me what moved, what is blocked, and the next operator actions.",
  },
  {
    id: "start-2",
    title: "Close a multi-app follow-up",
    description: "Assemble the inbox, Slack, and meeting trail before sending the next response.",
    category: "Multi-app follow-up",
    icon: "follow-up",
    seedPrompt:
      "Trace the latest customer follow-up across Gmail, Slack, and meeting notes. Show what changed, what still needs a response, and draft the cleanest next action.",
  },
  {
    id: "start-3",
    title: "Review an approval packet",
    description: "Open the human review context with provenance, recommendation, and business risk.",
    category: "Approval packet",
    icon: "approval",
    seedPrompt:
      "Open the highest-risk approval packet in the queue. Summarize the recommendation, confidence, business impact, and what I should approve, edit, or reject.",
  },
  {
    id: "start-4",
    title: "Prep the next meeting",
    description: "Turn linked email, project, and task context into a meeting pre-read.",
    category: "Meeting pre-read",
    icon: "meeting",
    seedPrompt:
      "Prepare a pre-read for the next meeting. Pull the open inbox threads, project context, and approvals that should be carried into the conversation.",
  },
  {
    id: "start-5",
    title: "Diagnose a workflow",
    description: "Inspect the latest run, artifacts, and approval state before deciding intervention.",
    category: "Workflow diagnosis",
    icon: "workflow",
    seedPrompt:
      "Diagnose the workflow that needs operator attention today. Show the current run state, recent artifacts, approval blockers, and the best next intervention.",
  },
  {
    id: "start-6",
    title: "Research with connectors",
    description: "Ground a fresh question in Drive, Calendar, and recent operational signals.",
    category: "Connector-grounded research",
    icon: "research",
    seedPrompt:
      "Start a connector-grounded research thread. Use Drive, Calendar, and recent operating signals to answer the question with sources and recommended next actions.",
  },
];

export const chatSignals: SignalItem[] = [
  {
    id: "signal-1",
    label: "Inbox requiring response",
    value: "12 items",
    description: "Open threads that still need a human response now.",
    href: "/inbox",
    tone: "alert",
  },
  {
    id: "signal-2",
    label: "Approvals waiting",
    value: "4 reviews",
    description: "Human-in-the-loop packets that are blocking downstream work.",
    href: "/approvals",
    tone: "alert",
  },
  {
    id: "signal-3",
    label: "Meetings today",
    value: "3 sessions",
    description: "Upcoming prep surfaces and follow-through that should stay linked.",
    href: "/meetings",
  },
  {
    id: "signal-4",
    label: "Workflow runs live",
    value: "2 executing",
    description: "Automations currently moving work or waiting on review.",
    href: "/workflows",
  },
];

export const chatRecentWork = [
  {
    id: "work-1",
    title: "Thai Union compliance thread",
    summary: "Context assembled from email, WhatsApp, and prior meeting notes.",
  },
  {
    id: "work-2",
    title: "Pricing monitor daily brief",
    summary: "Watchlist refreshed with margin anomalies across three suppliers.",
  },
  {
    id: "work-3",
    title: "Rotterdam inspection prep",
    summary: "Meeting prep packet and approval checklist generated for operator review.",
  },
];

export const inboxThreads: InboxThread[] = [
  {
    id: "thread-1",
    source: "Email",
    sender: "Sarah Kim",
    company: "Northstar Forwarding",
    subject: "Q2 rate confirmation requires executive response",
    preview: "The forwarder accepted the revised rate, but legal language on detention still needs your approval before we release the reply.",
    priority: "Critical",
    priorityBand: "needs_attention",
    owner: "Hemanth",
    waitingState: "Waiting on you",
    dueRisk: "Due in 2 hours",
    lastMaterialChangeAt: "08:42",
    lastReviewedAt: "Yesterday · 5:20 PM",
    whyThisMatters: "Commercial terms changed and the buyer is blocked on a same-day commitment.",
    whatChanged: "Legal wording narrowed the acceptable detention clause in the latest revision.",
    whatIsBlocked: "The outbound reply and PO release remain blocked until you approve the language.",
    nextAction: "Request approval and release the reply with the preserved detention clause.",
    account: "Redwood Foods",
    project: "Mumbai-Rotterdam Q2",
    participants: ["Sarah Kim", "Legal", "Hemanth"],
    approvalStatus: "approval_required",
    followUpStatus: "blocked_by_approval",
    delegationStatus: "none",
    attachmentPresence: true,
    linkedTask: { id: "task-101", label: "Release rate confirmation", status: "Blocked" },
    linkedWorkflow: {
      id: "workflow-201",
      label: "Sales PI to PO",
      status: "Awaiting approval",
      nextStep: "Send approved reply",
    },
    tags: ["External reply", "Margin risk"],
    time: "08:42",
    extractedTasks: [
      "Approve the reply draft",
      "Confirm detention clause language with legal",
      "Update the project thread after send",
    ],
    recommendedReply: "Approve with clause 4.2 preserved and copy legal on the outbound note.",
    timeline: [
      {
        id: "message-1a",
        sender: "Sarah Kim",
        role: "Forwarder",
        time: "Today · 08:42",
        body:
          "The forwarder accepted the revised rate. Legal wording on detention remains open. We need your sign-off before I release the reply to Redwood.",
        attachments: ["Contract redline.pdf", "Rate summary.xlsx"],
      },
      {
        id: "message-1b",
        sender: "Legal",
        role: "Internal note",
        time: "Yesterday · 06:18 PM",
        body:
          "Clause 4.2 can stand, but do not imply blanket detention coverage beyond the current window.",
        summary: "Legal approved the commercial position but limited the wording.",
      },
    ],
    contextModules: [
      {
        id: "people-company-1",
        title: "People and Company",
        items: [
          { label: "Primary contact", value: "Sarah Kim" },
          { label: "Role", value: "Forwarder" },
          { label: "Company", value: "Northstar Forwarding" },
          { label: "Relationship importance", value: "Tier 1 lane partner" },
        ],
      },
      {
        id: "account-project-1",
        title: "Account or Project Context",
        items: [
          { label: "Account", value: "Redwood Foods" },
          { label: "Project", value: "Mumbai-Rotterdam Q2" },
          { label: "Stage", value: "Rate confirmation" },
          { label: "Business object", value: "Contract MR-Q2 rev 3" },
        ],
      },
      {
        id: "commitments-1",
        title: "Commitments and Deadlines",
        items: [
          { label: "Last promise", value: "Reply today with approved commercial language" },
          { label: "Next expected action", value: "Approve draft and release reply" },
          { label: "Deadline", value: "Today · 11:00 AM PST" },
          { label: "Waiting state", value: "Waiting on you" },
        ],
      },
      {
        id: "crm-erp-1",
        title: "CRM and ERP Context",
        items: [
          { label: "CRM status", value: "Buyer decision pending" },
          { label: "ERP state", value: "PO release blocked" },
          { label: "Margin impact", value: "High if detention wording expands" },
          { label: "Blocker", value: "Approval required before send" },
        ],
      },
      {
        id: "linked-tasks-1",
        title: "Linked Tasks",
        items: [
          { label: "Task", value: "Release rate confirmation" },
          { label: "Owner", value: "Hemanth" },
          { label: "Due", value: "Today" },
          { label: "Status", value: "Blocked" },
        ],
      },
      {
        id: "linked-workflows-1",
        title: "Linked Workflows",
        items: [
          { label: "Workflow", value: "Sales PI to PO" },
          { label: "Run status", value: "Awaiting approval" },
          { label: "Next step", value: "Send approved reply" },
          { label: "Owner", value: "Commercial ops" },
        ],
      },
      {
        id: "related-meetings-1",
        title: "Related Meetings",
        items: [
          { label: "Next meeting", value: "Morning operator brief" },
          { label: "Time", value: "Today · 08:15 AM PST" },
          { label: "Focus", value: "Contract wording and release timing" },
        ],
      },
      {
        id: "files-1",
        title: "Attachments and Files",
        items: [
          { label: "Files", value: "Contract redline.pdf, Rate summary.xlsx" },
          { label: "Latest addition", value: "Revised contract rev 3" },
          { label: "Inspection state", value: "Inspectable" },
        ],
      },
      {
        id: "similar-outcomes-1",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Atlantic Fresh Q1 contract revision" },
          { label: "How handled", value: "Preserved legal clause and copied counsel" },
          { label: "Reuse pattern", value: "Approve draft, send, then update project log" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "request_approval",
        label: "Request approval",
        kind: "primary",
        description: "High-consequence external commitment requires sign-off before send.",
      },
      {
        key: "generate_reply",
        label: "Generate reply",
        kind: "secondary",
        description: "Preview the outbound language before approval.",
      },
      {
        key: "create_task",
        label: "Create or update task",
        kind: "secondary",
        description: "Keep the rate-release task linked to the thread.",
      },
      {
        key: "mark_reviewed",
        label: "Mark reviewed",
        kind: "tertiary",
        description: "Return the thread to watching after approval is handled.",
      },
    ],
    provenance: [
      { label: "Thread source", value: "Email thread: Sarah Kim -> You (today 08:42)" },
      { label: "Workflow", value: "Sales PI to PO" },
      { label: "Reference", value: "Contract MR-Q2 rev 3" },
      { label: "Reason surfaced", value: "New legal blocker on same-day buyer decision" },
    ],
    attachments: ["Contract redline.pdf", "Rate summary.xlsx"],
    approvalPacket: {
      actionType: "External reply",
      riskLevel: "High risk",
      whyApprovalNeeded: "Commercial commitment and detention language can change exposure before PO release.",
      businessImpact: "A delayed or incorrect response risks margin leakage and buyer confidence on a same-day deal.",
      target: "Sarah Kim and Redwood Foods commercial thread",
      editableOutput:
        "Approve with clause 4.2 preserved, confirm the revised rate, and copy legal on the outbound note before release.",
      sourceThread: "Q2 rate confirmation requires executive response",
      trace: [
        "Email thread with Sarah Kim",
        "Contract MR-Q2 rev 3",
        "Legal note from yesterday",
      ],
    },
    taskPacket: {
      mode: "update",
      taskTitle: "Release rate confirmation",
      owner: "Hemanth",
      dueDate: "Today · 11:00 AM PST",
      nextAction: "Approve and send the reply with preserved detention wording.",
      sourceThread: "Q2 rate confirmation requires executive response",
      workflowLinkage: "Sales PI to PO",
      approvalRequirement: "Required before send",
      currentStatus: "Blocked",
      delegationHistory: ["No delegation yet"],
      followUpPlan: "Update the project thread immediately after send.",
      linkedPlaybook: "Commercial reply review",
      linkedAgent: "Inbox triage agent",
    },
  },
  {
    id: "thread-2",
    source: "Slack",
    sender: "Raj Mehta",
    company: "Ops Desk",
    subject: "Cold-chain delay at Mumbai port",
    preview: "Customs hold has shifted the handoff window by six hours. Ops wants a decision on whether we inform the buyer now or wait for the inspection note.",
    priority: "High",
    priorityBand: "review_today",
    owner: "Ops desk",
    waitingState: "Waiting on ops",
    dueRisk: "Review today",
    lastMaterialChangeAt: "09:15",
    lastReviewedAt: "Today · 08:30 AM",
    whyThisMatters: "Buyer communication timing affects trust and may change the delivery expectation.",
    whatChanged: "Customs pushed the handoff window back by six hours this morning.",
    whatIsBlocked: "The buyer update is waiting on a decision about whether to communicate before inspection.",
    nextAction: "Decide whether to notify the buyer now with a provisional ETA.",
    account: "Marina Foods",
    project: "Mumbai-Rotterdam Q2",
    participants: ["Raj Mehta", "Port ops", "Buyer contact"],
    approvalStatus: "not_required",
    followUpStatus: "recommended",
    delegationStatus: "none",
    attachmentPresence: true,
    linkedTask: { id: "task-102", label: "Update delivery ETA", status: "Open" },
    linkedWorkflow: {
      id: "workflow-202",
      label: "Delay escalation",
      status: "Running",
      nextStep: "Notify buyer if inspection slips further",
    },
    tags: ["Delivery change", "Ops review"],
    time: "09:15",
    extractedTasks: ["Decide if buyer is notified now", "Link the delay to the project timeline"],
    recommendedReply: "Notify the buyer now with a provisional ETA and append inspection details once cleared.",
    timeline: [
      {
        id: "message-2a",
        sender: "Raj Mehta",
        role: "Ops lead",
        time: "Today · 09:15",
        body:
          "Customs hold moved the handoff by six hours. Ops needs a decision on whether to inform the buyer now or wait for the inspection note.",
        attachments: ["Port status note"],
      },
      {
        id: "message-2b",
        sender: "Ubik system",
        role: "System alert",
        time: "Today · 08:58",
        body: "Container YB-7221 triggered a schedule anomaly from the ERP handoff feed.",
      },
    ],
    contextModules: [
      {
        id: "people-company-2",
        title: "People and Company",
        items: [
          { label: "Primary contact", value: "Raj Mehta" },
          { label: "Role", value: "Ops lead" },
          { label: "Company", value: "Ops Desk" },
          { label: "Relationship importance", value: "Internal shipping owner" },
        ],
      },
      {
        id: "account-project-2",
        title: "Account or Project Context",
        items: [
          { label: "Account", value: "Marina Foods" },
          { label: "Project", value: "Mumbai-Rotterdam Q2" },
          { label: "Stage", value: "In transit" },
          { label: "Business object", value: "Container YB-7221" },
        ],
      },
      {
        id: "commitments-2",
        title: "Commitments and Deadlines",
        items: [
          { label: "Last promise", value: "Buyer to receive ETA update by midday" },
          { label: "Next expected action", value: "Decide notification timing" },
          { label: "Deadline", value: "Today · 12:00 PM PST" },
          { label: "Waiting state", value: "Waiting on ops" },
        ],
      },
      {
        id: "crm-erp-2",
        title: "CRM and ERP Context",
        items: [
          { label: "CRM status", value: "Account flagged for schedule sensitivity" },
          { label: "ERP state", value: "Inspection pending" },
          { label: "Blocker", value: "Inspection note not yet attached" },
        ],
      },
      {
        id: "linked-tasks-2",
        title: "Linked Tasks",
        items: [
          { label: "Task", value: "Update delivery ETA" },
          { label: "Owner", value: "Ops desk" },
          { label: "Due", value: "Today" },
          { label: "Status", value: "Open" },
        ],
      },
      {
        id: "linked-workflows-2",
        title: "Linked Workflows",
        items: [
          { label: "Workflow", value: "Delay escalation" },
          { label: "Run status", value: "Running" },
          { label: "Next step", value: "Send buyer note if risk rises" },
        ],
      },
      {
        id: "files-2",
        title: "Attachments and Files",
        items: [
          { label: "Files", value: "Port status note" },
          { label: "Latest addition", value: "Port status note" },
          { label: "Inspection state", value: "Inspection note still missing" },
        ],
      },
      {
        id: "similar-outcomes-2",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Q1 customs hold update" },
          { label: "How handled", value: "Sent provisional ETA before formal inspection note" },
          { label: "Reuse pattern", value: "Buyer updated early, then corrected with inspection data" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "generate_reply",
        label: "Generate reply",
        kind: "primary",
        description: "Draft the buyer update with a provisional ETA and inspection caveat.",
      },
      {
        key: "set_follow_up",
        label: "Set follow-up",
        kind: "secondary",
        description: "Schedule a follow-up once the inspection note lands.",
      },
      {
        key: "run_workflow",
        label: "Run workflow",
        kind: "secondary",
        description: "Escalate through the delay playbook if the window slips again.",
      },
    ],
    provenance: [
      { label: "Slack source", value: "Channel: logistics-ops" },
      { label: "System alert", value: "Container YB-7221 anomaly" },
      { label: "Meeting note", value: "Yesterday logistics sync" },
      { label: "Reason surfaced", value: "Timeline change with buyer communication risk" },
    ],
    attachments: ["Port status note"],
    taskPacket: {
      mode: "update",
      taskTitle: "Update delivery ETA",
      owner: "Ops desk",
      dueDate: "Today · 12:00 PM PST",
      nextAction: "Decide whether to notify the buyer now or after inspection.",
      sourceThread: "Cold-chain delay at Mumbai port",
      workflowLinkage: "Delay escalation",
      approvalRequirement: "Not required",
      currentStatus: "Open",
      delegationHistory: ["Assigned to ops desk during morning review"],
      followUpPlan: "Recheck inspection note in 90 minutes.",
      linkedPlaybook: "Delay escalation",
      linkedAgent: "Logistics monitor",
    },
  },
  {
    id: "thread-3",
    source: "WhatsApp",
    sender: "Thai Union Ops",
    company: "Thai Union",
    subject: "Compliance documents uploaded late",
    preview: "Supplier asks for a 24-hour extension to upload the remaining HACCP certificates and wants confirmation that the workflow will not block the PO.",
    priority: "High",
    priorityBand: "waiting_on_you",
    owner: "Compliance",
    waitingState: "Waiting on you",
    dueRisk: "Due today",
    lastMaterialChangeAt: "10:07",
    lastReviewedAt: "Yesterday · 03:12 PM",
    whyThisMatters: "The supplier extension changes the PO release path and touches compliance policy.",
    whatChanged: "The supplier requested a 24-hour extension and uploaded only a partial proof artifact.",
    whatIsBlocked: "The PO stays gated until the extension is approved and the remaining files are validated.",
    nextAction: "Decide whether to allow the extension and keep PO release in manual approval mode.",
    account: "Thai Union",
    project: "Supplier Compliance Audit",
    participants: ["Thai Union Ops", "Compliance", "Procurement"],
    approvalStatus: "approval_required",
    followUpStatus: "due_soon",
    delegationStatus: "suggested",
    attachmentPresence: true,
    linkedTask: { id: "task-103", label: "Review extension request", status: "Open" },
    linkedWorkflow: {
      id: "workflow-203",
      label: "Compliance monitoring",
      status: "Manual review",
      nextStep: "Hold PO until files validate",
    },
    tags: ["Approval", "Compliance"],
    time: "10:07",
    extractedTasks: ["Review extension request", "Decide whether to unblock PO"],
    recommendedReply: "Allow the extension but keep the workflow in manual approval mode until files are validated.",
    timeline: [
      {
        id: "message-3a",
        sender: "Thai Union Ops",
        role: "Supplier ops",
        time: "Today · 10:07",
        body:
          "We need 24 more hours for the remaining HACCP certificates. Please confirm the PO workflow will not block while we finish the upload.",
        attachments: ["HACCP renewal screenshot"],
      },
      {
        id: "message-3b",
        sender: "Compliance Bot",
        role: "System note",
        time: "Today · 09:49",
        body: "The supplier exception rule moved this thread back into manual approval.",
        summary: "Policy requires manual review for late compliance documents.",
      },
    ],
    contextModules: [
      {
        id: "people-company-3",
        title: "People and Company",
        items: [
          { label: "Primary contact", value: "Thai Union Ops" },
          { label: "Role", value: "Supplier ops" },
          { label: "Company", value: "Thai Union" },
          { label: "Relationship importance", value: "High-volume supplier" },
        ],
      },
      {
        id: "account-project-3",
        title: "Account or Project Context",
        items: [
          { label: "Account", value: "Thai Union" },
          { label: "Project", value: "Supplier Compliance Audit" },
          { label: "Stage", value: "Document exception" },
          { label: "Business object", value: "PO release gate" },
        ],
      },
      {
        id: "commitments-3",
        title: "Commitments and Deadlines",
        items: [
          { label: "Last promise", value: "Confirm PO posture after document check" },
          { label: "Next expected action", value: "Approve or deny extension" },
          { label: "Deadline", value: "Today · 04:00 PM PST" },
          { label: "Waiting state", value: "Waiting on you" },
        ],
      },
      {
        id: "crm-erp-3",
        title: "CRM and ERP Context",
        items: [
          { label: "CRM status", value: "Supplier relationship sensitive" },
          { label: "ERP state", value: "PO blocked by compliance gate" },
          { label: "Blocker", value: "Remaining HACCP files not yet validated" },
        ],
      },
      {
        id: "linked-tasks-3",
        title: "Linked Tasks",
        items: [
          { label: "Task", value: "Review extension request" },
          { label: "Owner", value: "Compliance" },
          { label: "Due", value: "Today" },
          { label: "Status", value: "Open" },
        ],
      },
      {
        id: "linked-workflows-3",
        title: "Linked Workflows",
        items: [
          { label: "Workflow", value: "Compliance monitoring" },
          { label: "Run status", value: "Manual review" },
          { label: "Next step", value: "Validate remaining files" },
        ],
      },
      {
        id: "files-3",
        title: "Attachments and Files",
        items: [
          { label: "Files", value: "HACCP renewal screenshot" },
          { label: "Latest addition", value: "Renewal screenshot uploaded today" },
          { label: "Inspection state", value: "Full certificates still pending" },
        ],
      },
      {
        id: "similar-outcomes-3",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Vendor certificate late upload, February" },
          { label: "How handled", value: "Granted 24 hours with manual PO hold" },
          { label: "Reuse pattern", value: "Approve extension, hold PO, re-check documents" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "request_approval",
        label: "Request approval",
        kind: "primary",
        description: "The supplier exception still requires a manual approval decision.",
      },
      {
        key: "create_task",
        label: "Create or update task",
        kind: "secondary",
        description: "Track document validation and PO release together.",
      },
      {
        key: "suggest_delegate",
        label: "Suggest delegate",
        kind: "secondary",
        description: "Recommend compliance as the owner for the next step.",
      },
    ],
    provenance: [
      { label: "WhatsApp source", value: "Contact: Thai Union Ops" },
      { label: "Approval queue", value: "Supplier exception" },
      { label: "Project", value: "Supplier Compliance Audit" },
      { label: "Reason surfaced", value: "Late compliance documents with PO release risk" },
    ],
    attachments: ["HACCP renewal screenshot"],
    approvalPacket: {
      actionType: "Workflow approval",
      riskLevel: "High risk",
      whyApprovalNeeded: "The extension changes a compliance gate and could unblock a PO before validation completes.",
      businessImpact: "Approving incorrectly can create compliance exposure; delaying too long can disrupt supply timing.",
      target: "Compliance monitoring workflow",
      editableOutput:
        "Allow the 24-hour extension, keep the PO in manual review, and require full certificate validation before release.",
      sourceThread: "Compliance documents uploaded late",
      trace: [
        "WhatsApp note from Thai Union Ops",
        "Supplier Compliance Audit project",
        "Policy watch brief on document freshness",
      ],
    },
    taskPacket: {
      mode: "update",
      taskTitle: "Review extension request",
      owner: "Compliance",
      dueDate: "Today · 04:00 PM PST",
      nextAction: "Approve or deny the supplier extension and confirm PO release posture.",
      sourceThread: "Compliance documents uploaded late",
      workflowLinkage: "Compliance monitoring",
      approvalRequirement: "Required before workflow update",
      currentStatus: "Open",
      delegationHistory: ["Suggested owner: Compliance"],
      followUpPlan: "Check for full certificate upload tomorrow morning.",
      linkedPlaybook: "Supplier exception review",
      linkedAgent: "Compliance Bot",
    },
  },
  {
    id: "thread-4",
    source: "Email",
    sender: "Alicia Torres",
    company: "Harbor Retail",
    subject: "Still waiting on revised delivery note",
    preview: "The buyer is following up on the note you promised yesterday and has not received an updated ETA yet.",
    priority: "High",
    priorityBand: "follow_up_risk",
    owner: "Hemanth",
    waitingState: "Waiting on you",
    dueRisk: "Overdue by 1 day",
    lastMaterialChangeAt: "07:24",
    lastReviewedAt: "Yesterday · 09:10 AM",
    whyThisMatters: "A missed commitment is now visible to the buyer and risks trust on an already delayed lane.",
    whatChanged: "The buyer followed up because the revised note promised yesterday never went out.",
    whatIsBlocked: "The relationship resets only after a fresh note and follow-up checkpoint are sent.",
    nextAction: "Send the revised delivery note or schedule a follow-up immediately.",
    account: "Harbor Retail",
    project: "Atlantic Fresh Q3",
    participants: ["Alicia Torres", "Ops desk", "Finance"],
    approvalStatus: "not_required",
    followUpStatus: "overdue",
    delegationStatus: "none",
    attachmentPresence: false,
    linkedTask: { id: "task-104", label: "Send revised delivery note", status: "Overdue" },
    tags: ["Follow-up risk", "Buyer waiting"],
    time: "07:24",
    extractedTasks: ["Send the revised delivery note", "Reset buyer expectation with a new ETA"],
    recommendedReply: "Acknowledge the delay, share the revised ETA, and commit to the next checkpoint time.",
    timeline: [
      {
        id: "message-4a",
        sender: "Alicia Torres",
        role: "Buyer",
        time: "Today · 07:24",
        body:
          "Following up on the revised delivery note you said would arrive yesterday. We still do not have the updated ETA.",
      },
      {
        id: "message-4b",
        sender: "You",
        role: "Last outbound",
        time: "Yesterday · 10:12 AM",
        body: "I will send an updated delivery note by end of day once ops confirms the revised timing.",
        summary: "A commitment was made and missed.",
      },
    ],
    contextModules: [
      {
        id: "people-company-4",
        title: "People and Company",
        items: [
          { label: "Primary contact", value: "Alicia Torres" },
          { label: "Role", value: "Buyer" },
          { label: "Company", value: "Harbor Retail" },
          { label: "Relationship importance", value: "Sensitive renewal account" },
        ],
      },
      {
        id: "account-project-4",
        title: "Account or Project Context",
        items: [
          { label: "Account", value: "Harbor Retail" },
          { label: "Project", value: "Atlantic Fresh Q3" },
          { label: "Stage", value: "Delivery delay" },
          { label: "Business object", value: "Buyer ETA note" },
        ],
      },
      {
        id: "commitments-4",
        title: "Commitments and Deadlines",
        items: [
          { label: "Last promise", value: "Updated delivery note by yesterday EOD" },
          { label: "Next expected action", value: "Send revised delivery note" },
          { label: "Deadline", value: "Overdue by 1 day" },
          { label: "Waiting state", value: "Waiting on you" },
        ],
      },
      {
        id: "crm-erp-4",
        title: "CRM and ERP Context",
        items: [
          { label: "CRM status", value: "Account flagged for follow-up discipline" },
          { label: "ERP state", value: "Revised ETA available" },
          { label: "Blocker", value: "Outbound note still unsent" },
        ],
      },
      {
        id: "linked-tasks-4",
        title: "Linked Tasks",
        items: [
          { label: "Task", value: "Send revised delivery note" },
          { label: "Owner", value: "Hemanth" },
          { label: "Due", value: "Yesterday" },
          { label: "Status", value: "Overdue" },
        ],
      },
      {
        id: "similar-outcomes-4",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Q2 buyer ETA correction" },
          { label: "How handled", value: "Sent apology plus precise next checkpoint" },
          { label: "Reuse pattern", value: "Acknowledge, update ETA, lock next follow-up" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "set_follow_up",
        label: "Set follow-up",
        kind: "primary",
        description: "Reset the missed commitment with a new time-bound checkpoint.",
      },
      {
        key: "generate_reply",
        label: "Generate reply",
        kind: "secondary",
        description: "Draft the buyer-facing follow-up note.",
      },
      {
        key: "create_task",
        label: "Create or update task",
        kind: "secondary",
        description: "Keep the overdue commitment visible until it is sent.",
      },
    ],
    provenance: [
      { label: "Email source", value: "Buyer follow-up this morning" },
      { label: "Last promise", value: "Updated delivery note promised yesterday" },
      { label: "Reason surfaced", value: "Follow-up commitment is overdue" },
    ],
    attachments: [],
    taskPacket: {
      mode: "update",
      taskTitle: "Send revised delivery note",
      owner: "Hemanth",
      dueDate: "Overdue",
      nextAction: "Send the revised ETA note and schedule a checkpoint update.",
      sourceThread: "Still waiting on revised delivery note",
      workflowLinkage: "None linked",
      approvalRequirement: "Not required",
      currentStatus: "Overdue",
      delegationHistory: ["No delegation yet"],
      followUpPlan: "Schedule a buyer checkpoint for tomorrow morning.",
      linkedPlaybook: "Buyer delay recovery",
      linkedAgent: "Follow-up monitor",
    },
  },
  {
    id: "thread-5",
    source: "System",
    sender: "Workflow monitor",
    company: "Ubik",
    subject: "Daily pricing workflow completed",
    preview: "The monitor finished normally and flagged two margin anomalies in the Atlantic Fresh lane. Review is optional unless action is required.",
    priority: "Medium",
    priorityBand: "auto_handled",
    owner: "Automations",
    waitingState: "Watching",
    dueRisk: "No deadline",
    lastMaterialChangeAt: "06:00",
    lastReviewedAt: "Today · 06:12 AM",
    whyThisMatters: "Ubik handled the routine digest, but two anomalies remain inspectable if margin risk grows.",
    whatChanged: "The daily monitor completed and published a new pricing brief with two anomalies.",
    whatIsBlocked: "Nothing is blocked unless the next run confirms a deeper margin issue.",
    nextAction: "Review only if the anomaly persists in the next run.",
    account: "Atlantic Fresh",
    project: "Atlantic Fresh Q3",
    participants: ["Pricing monitor", "Finance agent"],
    approvalStatus: "approved",
    followUpStatus: "auto_handled",
    delegationStatus: "none",
    attachmentPresence: true,
    linkedWorkflow: {
      id: "workflow-204",
      label: "Daily pricing workflow",
      status: "Completed",
      nextStep: "Watch the next run",
    },
    tags: ["Auto-handled", "Watch"],
    time: "06:00",
    extractedTasks: ["Review anomalies if margin dips continue"],
    recommendedReply: "No outbound response required.",
    timeline: [
      {
        id: "message-5a",
        sender: "Workflow monitor",
        role: "System",
        time: "Today · 06:00",
        body: "Run 842 completed and published the pricing brief with two margin anomalies flagged.",
        attachments: ["pricing-brief.html"],
      },
    ],
    contextModules: [
      {
        id: "linked-workflows-5",
        title: "Linked Workflows",
        items: [
          { label: "Workflow", value: "Daily pricing workflow" },
          { label: "Run status", value: "Completed" },
          { label: "Next step", value: "Watch the next run" },
        ],
      },
      {
        id: "files-5",
        title: "Attachments and Files",
        items: [
          { label: "Files", value: "pricing-brief.html" },
          { label: "Latest addition", value: "Daily pricing brief" },
          { label: "Inspection state", value: "Ready to inspect" },
        ],
      },
      {
        id: "similar-outcomes-5",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Run 841 pricing watch" },
          { label: "How handled", value: "Watched only, no escalation" },
          { label: "Reuse pattern", value: "Inspect only if anomalies persist" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "analyze_attachments",
        label: "Analyze attachments",
        kind: "primary",
        description: "Inspect the brief if the anomalies need a closer read.",
      },
      {
        key: "watch",
        label: "Mark watching",
        kind: "secondary",
        description: "Keep the thread quiet unless the next run worsens.",
      },
    ],
    provenance: [
      { label: "Workflow run", value: "Run 842" },
      { label: "Artifact", value: "Daily pricing brief" },
      { label: "Source systems", value: "ERP, supplier feeds" },
      { label: "Reason surfaced", value: "Auto-handled summary with inspectable anomalies" },
    ],
    attachments: ["pricing-brief.html"],
    taskPacket: {
      mode: "create",
      taskTitle: "Review pricing anomalies",
      owner: "Finance",
      dueDate: "Tomorrow · 06:30 AM PST",
      nextAction: "Review only if the next run confirms the anomalies.",
      sourceThread: "Daily pricing workflow completed",
      workflowLinkage: "Daily pricing workflow",
      approvalRequirement: "Not required",
      currentStatus: "Watching",
      delegationHistory: ["Handled by Pricing monitor"],
      followUpPlan: "Watch tomorrow's run before creating a human task.",
      linkedPlaybook: "Pricing anomaly review",
      linkedAgent: "Pricing monitor",
    },
  },
  {
    id: "thread-6",
    source: "Email",
    sender: "Jordan Bell",
    company: "Harbor Retail",
    subject: "Buyer asks whether partial shipment can move first",
    preview: "The buyer is asking for a partial release option while the remaining inventory clears inspection.",
    priority: "Medium",
    priorityBand: "awaiting_approval",
    owner: "Commercial ops",
    waitingState: "Awaiting approval",
    dueRisk: "Decision today",
    lastMaterialChangeAt: "11:05",
    lastReviewedAt: "Today · 10:10 AM",
    whyThisMatters: "The partial-shipment answer changes customer expectation and requires controlled approval.",
    whatChanged: "Commercial ops drafted a split-release response and finance threshold review is still pending.",
    whatIsBlocked: "The buyer reply cannot be sent until the exception language is approved.",
    nextAction: "Approve or edit the partial-shipment response before commercial ops sends it.",
    account: "Harbor Retail",
    project: "Atlantic Fresh Q3",
    participants: ["Jordan Bell", "Commercial ops", "Finance"],
    approvalStatus: "approval_required",
    followUpStatus: "blocked_by_approval",
    delegationStatus: "none",
    attachmentPresence: false,
    linkedTask: { id: "task-105", label: "Approve partial shipment response", status: "Blocked" },
    tags: ["Approval", "Commercial reply"],
    time: "11:05",
    extractedTasks: ["Review the partial shipment language", "Confirm whether finance accepts the split release"],
    recommendedReply: "Approve the partial release response only if the financial exposure stays within the agreed threshold.",
    timeline: [
      {
        id: "message-6a",
        sender: "Jordan Bell",
        role: "Buyer contact",
        time: "Today · 11:05",
        body:
          "Can we move a partial shipment first while the remaining inventory clears inspection? We need an answer today.",
      },
      {
        id: "message-6b",
        sender: "Commercial ops",
        role: "Draft owner",
        time: "Today · 10:47",
        body:
          "Drafted a reply that allows a split release if finance confirms exposure stays within threshold.",
        summary: "Draft ready, finance threshold still needs sign-off.",
      },
    ],
    contextModules: [
      {
        id: "people-company-6",
        title: "People and Company",
        items: [
          { label: "Primary contact", value: "Jordan Bell" },
          { label: "Role", value: "Buyer contact" },
          { label: "Company", value: "Harbor Retail" },
          { label: "Relationship importance", value: "Renewal account" },
        ],
      },
      {
        id: "account-project-6",
        title: "Account or Project Context",
        items: [
          { label: "Account", value: "Harbor Retail" },
          { label: "Project", value: "Atlantic Fresh Q3" },
          { label: "Stage", value: "Delivery exception" },
          { label: "Business object", value: "Partial shipment response" },
        ],
      },
      {
        id: "commitments-6",
        title: "Commitments and Deadlines",
        items: [
          { label: "Last promise", value: "Provide a decision today" },
          { label: "Next expected action", value: "Approve or edit the response" },
          { label: "Deadline", value: "Today · 03:00 PM PST" },
          { label: "Waiting state", value: "Awaiting approval" },
        ],
      },
      {
        id: "crm-erp-6",
        title: "CRM and ERP Context",
        items: [
          { label: "CRM status", value: "Account watching delivery variance closely" },
          { label: "ERP state", value: "Partial inventory can move" },
          { label: "Blocker", value: "Finance exposure threshold not approved" },
        ],
      },
      {
        id: "linked-tasks-6",
        title: "Linked Tasks",
        items: [
          { label: "Task", value: "Approve partial shipment response" },
          { label: "Owner", value: "Commercial ops" },
          { label: "Due", value: "Today" },
          { label: "Status", value: "Blocked" },
        ],
      },
      {
        id: "similar-outcomes-6",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Q2 split shipment request" },
          { label: "How handled", value: "Approved only after finance threshold check" },
          { label: "Reuse pattern", value: "Finance sign-off before buyer confirmation" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "request_approval",
        label: "Request approval",
        kind: "primary",
        description: "The buyer-facing split-release response needs sign-off before send.",
      },
      {
        key: "generate_reply",
        label: "Generate reply",
        kind: "secondary",
        description: "Inspect the outbound wording before approval.",
      },
      {
        key: "mark_reviewed",
        label: "Mark reviewed",
        kind: "tertiary",
        description: "Move the thread back to review-today after approval is complete.",
      },
    ],
    provenance: [
      { label: "Email source", value: "Buyer request received at 11:05" },
      { label: "Draft owner", value: "Commercial ops" },
      { label: "Reason surfaced", value: "Buyer-facing exception requires approval" },
    ],
    attachments: [],
    approvalPacket: {
      actionType: "External reply",
      riskLevel: "Medium risk",
      whyApprovalNeeded: "The split release changes customer expectation and creates financial exposure if inventory moves in parts.",
      businessImpact: "A controlled approval protects the account while avoiding an unsupported commitment.",
      target: "Harbor Retail buyer thread",
      editableOutput:
        "Confirm that a partial release is possible only within the finance-approved exposure threshold, and commit to a final timing update after inspection clears.",
      sourceThread: "Buyer asks whether partial shipment can move first",
      trace: [
        "Buyer email at 11:05",
        "Commercial ops draft at 10:47",
        "Finance threshold rule",
      ],
    },
    taskPacket: {
      mode: "update",
      taskTitle: "Approve partial shipment response",
      owner: "Commercial ops",
      dueDate: "Today · 03:00 PM PST",
      nextAction: "Approve or edit the buyer response.",
      sourceThread: "Buyer asks whether partial shipment can move first",
      workflowLinkage: "None linked",
      approvalRequirement: "Required before send",
      currentStatus: "Blocked",
      delegationHistory: ["Draft prepared by Commercial ops"],
      followUpPlan: "Update the buyer once finance confirms the threshold.",
      linkedPlaybook: "Delivery exception review",
      linkedAgent: "Commercial ops assistant",
    },
  },
  {
    id: "thread-7",
    source: "Email",
    sender: "Nina Patel",
    company: "Finance",
    subject: "Margin review package assigned to sales ops",
    preview: "Finance pushed the margin review package to sales ops for an initial pass and asked Ubik to keep you posted only if exceptions remain unresolved.",
    priority: "Medium",
    priorityBand: "delegated",
    owner: "Sales ops",
    waitingState: "Delegated to sales ops",
    dueRisk: "Watching today",
    lastMaterialChangeAt: "09:40",
    lastReviewedAt: "Today · 09:45 AM",
    whyThisMatters: "The work is delegated, but unresolved exceptions on the same account still matter.",
    whatChanged: "Finance reassigned the first-pass review to sales ops this morning.",
    whatIsBlocked: "Nothing is blocked for you unless the delegated owner cannot close the exception.",
    nextAction: "Monitor the delegated owner and step back in only if the exception persists.",
    account: "Atlantic Fresh",
    project: "Atlantic Fresh Q3",
    participants: ["Nina Patel", "Sales ops", "Finance"],
    approvalStatus: "not_required",
    followUpStatus: "recommended",
    delegationStatus: "delegated",
    attachmentPresence: true,
    linkedTask: { id: "task-106", label: "Review margin package", status: "In progress" },
    tags: ["Delegated", "Finance"],
    time: "09:40",
    extractedTasks: ["Watch delegated review", "Re-enter only if exceptions remain"],
    recommendedReply: "No immediate reply needed. Stay watching until sales ops finishes the first pass.",
    timeline: [
      {
        id: "message-7a",
        sender: "Nina Patel",
        role: "Finance",
        time: "Today · 09:40",
        body:
          "We assigned the margin review package to sales ops for the first pass. Please only re-enter if exceptions remain unresolved.",
        attachments: ["margin-package.pdf"],
      },
    ],
    contextModules: [
      {
        id: "people-company-7",
        title: "People and Company",
        items: [
          { label: "Primary contact", value: "Nina Patel" },
          { label: "Role", value: "Finance lead" },
          { label: "Company", value: "Finance" },
          { label: "Relationship importance", value: "Internal approval partner" },
        ],
      },
      {
        id: "linked-tasks-7",
        title: "Linked Tasks",
        items: [
          { label: "Task", value: "Review margin package" },
          { label: "Owner", value: "Sales ops" },
          { label: "Due", value: "Today" },
          { label: "Status", value: "In progress" },
        ],
      },
      {
        id: "files-7",
        title: "Attachments and Files",
        items: [
          { label: "Files", value: "margin-package.pdf" },
          { label: "Latest addition", value: "Margin package" },
          { label: "Inspection state", value: "Ready to inspect" },
        ],
      },
      {
        id: "similar-outcomes-7",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Q2 finance review handoff" },
          { label: "How handled", value: "Stayed watching until exception escalated" },
          { label: "Reuse pattern", value: "Delegate, monitor, then step in only if needed" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "watch",
        label: "Mark watching",
        kind: "primary",
        description: "Keep the delegated thread visible but quiet unless risk returns.",
      },
      {
        key: "suggest_delegate",
        label: "Suggest delegate",
        kind: "secondary",
        description: "Reassign if sales ops cannot finish the first pass.",
      },
      {
        key: "create_task",
        label: "Create or update task",
        kind: "secondary",
        description: "Keep the delegated task linked to the account.",
      },
    ],
    provenance: [
      { label: "Email source", value: "Finance handoff note" },
      { label: "Delegated owner", value: "Sales ops" },
      { label: "Reason surfaced", value: "Delegated thread still linked to a priority account" },
    ],
    attachments: ["margin-package.pdf"],
    taskPacket: {
      mode: "update",
      taskTitle: "Review margin package",
      owner: "Sales ops",
      dueDate: "Today · 05:00 PM PST",
      nextAction: "Complete the first pass and escalate unresolved exceptions only if needed.",
      sourceThread: "Margin review package assigned to sales ops",
      workflowLinkage: "None linked",
      approvalRequirement: "Not required",
      currentStatus: "In progress",
      delegationHistory: ["Delegated from finance to sales ops today"],
      followUpPlan: "Recheck at 4 PM if the package is still unresolved.",
      linkedPlaybook: "Margin review",
      linkedAgent: "Finance agent",
    },
  },
  {
    id: "thread-8",
    source: "Slack",
    sender: "Workflow monitor",
    company: "Ubik",
    subject: "Inspection notes posted, no action needed unless customer asks",
    preview: "The inspection notes are now linked into the project thread and no human action is needed unless the buyer requests a revised note.",
    priority: "Medium",
    priorityBand: "watching",
    owner: "Automations",
    waitingState: "Watching",
    dueRisk: "No deadline",
    lastMaterialChangeAt: "08:10",
    lastReviewedAt: "Today · 08:15 AM",
    whyThisMatters: "The thread changed, but the system already closed the operational gap unless a customer follow-up arrives.",
    whatChanged: "Inspection notes were attached to the project thread automatically.",
    whatIsBlocked: "Nothing is blocked unless the buyer asks for a revised note.",
    nextAction: "Keep watching and reopen only if the buyer asks for a revised note.",
    account: "Marina Foods",
    project: "Mumbai-Rotterdam Q2",
    participants: ["Workflow monitor", "Ops desk"],
    approvalStatus: "approved",
    followUpStatus: "none",
    delegationStatus: "none",
    attachmentPresence: true,
    linkedWorkflow: {
      id: "workflow-205",
      label: "Inspection trace",
      status: "Completed",
      nextStep: "Watch for buyer questions",
    },
    tags: ["Watching", "Auto-updated"],
    time: "08:10",
    extractedTasks: ["Watch for buyer follow-up"],
    recommendedReply: "No reply needed unless the buyer asks for an updated delivery note.",
    timeline: [
      {
        id: "message-8a",
        sender: "Workflow monitor",
        role: "System",
        time: "Today · 08:10",
        body: "Inspection notes were attached to the project thread automatically. No operator action is needed right now.",
        attachments: ["inspection-note.pdf"],
      },
    ],
    contextModules: [
      {
        id: "linked-workflows-8",
        title: "Linked Workflows",
        items: [
          { label: "Workflow", value: "Inspection trace" },
          { label: "Run status", value: "Completed" },
          { label: "Next step", value: "Watch for buyer questions" },
        ],
      },
      {
        id: "files-8",
        title: "Attachments and Files",
        items: [
          { label: "Files", value: "inspection-note.pdf" },
          { label: "Latest addition", value: "Inspection note" },
          { label: "Inspection state", value: "Attached to project" },
        ],
      },
      {
        id: "similar-outcomes-8",
        title: "Similar Past Outcomes",
        items: [
          { label: "Comparable thread", value: "Inspection note auto-link, March" },
          { label: "How handled", value: "Watched until buyer follow-up" },
          { label: "Reuse pattern", value: "Stay quiet unless the customer asks" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "watch",
        label: "Mark watching",
        kind: "primary",
        description: "Keep the thread quiet while the system handles the context update.",
      },
      {
        key: "analyze_attachments",
        label: "Analyze attachments",
        kind: "secondary",
        description: "Inspect the inspection note if a customer question arrives.",
      },
    ],
    provenance: [
      { label: "Slack source", value: "Workflow monitor update" },
      { label: "Artifact", value: "inspection-note.pdf" },
      { label: "Reason surfaced", value: "New attachment linked into an active project" },
    ],
    attachments: ["inspection-note.pdf"],
    taskPacket: {
      mode: "create",
      taskTitle: "Inspect inspection note if needed",
      owner: "Ops desk",
      dueDate: "No deadline",
      nextAction: "Only inspect if the buyer asks for a revised note.",
      sourceThread: "Inspection notes posted, no action needed unless customer asks",
      workflowLinkage: "Inspection trace",
      approvalRequirement: "Not required",
      currentStatus: "Watching",
      delegationHistory: ["Handled automatically by Workflow monitor"],
      followUpPlan: "Reopen only if customer follow-up lands.",
      linkedPlaybook: "Inspection note watch",
      linkedAgent: "Workflow monitor",
    },
  },
  {
    id: "thread-9",
    source: "System",
    sender: "Archive service",
    company: "Ubik",
    subject: "Resolved: Rotterdam inspection packet filed",
    preview: "The inspection packet is complete, the linked tasks are closed, and the thread is ready for archive view only.",
    priority: "Medium",
    priorityBand: "archive",
    owner: "Automations",
    waitingState: "Resolved",
    dueRisk: "None",
    lastMaterialChangeAt: "Yesterday · 05:10 PM",
    lastReviewedAt: "Yesterday · 05:30 PM",
    whyThisMatters: "This thread is resolved and retained only for traceability.",
    whatChanged: "The inspection packet was finalized and all linked tasks were closed.",
    whatIsBlocked: "Nothing is blocked.",
    nextAction: "No further action needed.",
    account: "Marina Foods",
    project: "Rotterdam inspection prep",
    participants: ["Archive service"],
    approvalStatus: "approved",
    followUpStatus: "none",
    delegationStatus: "none",
    attachmentPresence: true,
    tags: ["Archive"],
    time: "Yesterday",
    extractedTasks: ["None"],
    recommendedReply: "No reply required.",
    timeline: [
      {
        id: "message-9a",
        sender: "Archive service",
        role: "System",
        time: "Yesterday · 05:10 PM",
        body: "Inspection packet filed, linked tasks closed, and thread moved to archive.",
        attachments: ["inspection-packet.zip"],
      },
    ],
    contextModules: [
      {
        id: "files-9",
        title: "Attachments and Files",
        items: [
          { label: "Files", value: "inspection-packet.zip" },
          { label: "Latest addition", value: "Final inspection packet" },
          { label: "Inspection state", value: "Archived" },
        ],
      },
    ],
    actionRecommendations: [
      {
        key: "archive",
        label: "Archive",
        kind: "primary",
        description: "Keep the resolved thread in archive-only view.",
      },
    ],
    provenance: [
      { label: "Archive source", value: "Archive service" },
      { label: "Reason surfaced", value: "Resolved thread retained for traceability" },
    ],
    attachments: ["inspection-packet.zip"],
    taskPacket: {
      mode: "create",
      taskTitle: "No task needed",
      owner: "Automations",
      dueDate: "None",
      nextAction: "No follow-up required.",
      sourceThread: "Resolved: Rotterdam inspection packet filed",
      workflowLinkage: "None linked",
      approvalRequirement: "Not required",
      currentStatus: "Done",
      delegationHistory: ["Resolved by archive service"],
      followUpPlan: "No follow-up required.",
      linkedPlaybook: "Archive retention",
      linkedAgent: "Archive service",
    },
  },
];

export const meetings: MeetingRecord[] = [
  {
    id: "meeting-1",
    title: "Supplier review - Thai Union",
    time: "Today · 10:30 AM PST",
    stage: "Upcoming",
    owner: "Hemanth",
    participants: ["Raj Mehta", "Thai Union Ops", "Compliance Bot"],
    summary: "Prep review for delayed documentation and exception handling before PO release.",
    agenda: [
      "Confirm missing compliance documents",
      "Decide extension terms",
      "Set follow-up owner and deadline",
    ],
    decisions: ["Pending live meeting"],
    actionItems: ["Carry forward current approval recommendation into the meeting"],
  },
  {
    id: "meeting-2",
    title: "Logistics sync - Maersk",
    time: "Today · 2:00 PM PST",
    stage: "Upcoming",
    owner: "Ops desk",
    participants: ["Sarah Kim", "Port ops", "Logistics Bot"],
    summary: "Review container delays, revised arrival windows, and customer notification cadence.",
    agenda: ["Validate revised ETA", "Confirm customer comms", "Check inspection timing"],
    decisions: ["Pending live meeting"],
    actionItems: ["Bring open inbox threads related to YB-7221"],
  },
  {
    id: "meeting-3",
    title: "Morning operator brief",
    time: "Today · 8:15 AM PST",
    stage: "Completed",
    owner: "Ubik",
    participants: ["Hemanth", "Pricing monitor", "Inbox triage agent"],
    summary: "Reviewed top risk items, upcoming meetings, and overnight workflow outcomes.",
    agenda: ["Inbox risk", "Approvals", "Pricing monitor"],
    decisions: [
      "Escalate Thai Union exception to approval queue",
      "Keep pricing monitor in daily cadence",
    ],
    actionItems: ["Reply to Sarah on rate confirmation", "Prepare supplier review packet"],
  },
];

export const contactCards: ContactCard[] = [
  {
    id: "contact-hemanth",
    name: "Hemanth Rao",
    role: "Operator",
    company: "UBIK",
    domain: "ubik.ai",
    avatarSrc: "/avatars/hemanth.svg",
    avatarFallback: "HR",
  },
  {
    id: "contact-sarah",
    name: "Sarah Kim",
    role: "Logistics Manager",
    company: "Maersk",
    domain: "maersk.com",
    avatarSrc: "/avatars/sarah.svg",
    avatarFallback: "SK",
  },
  {
    id: "contact-raj",
    name: "Raj Mehta",
    role: "Plant Ops Lead",
    company: "Thai Union Ops",
    domain: "thaiunion.com",
    avatarSrc: "/avatars/raj.svg",
    avatarFallback: "RM",
  },
  {
    id: "contact-ana",
    name: "Ana Volkova",
    role: "Finance Controller",
    company: "Atlantic Fresh",
    domain: "atlanticfreshseafood.com",
    avatarSrc: "/avatars/ana.svg",
    avatarFallback: "AV",
  },
  {
    id: "contact-maya",
    name: "Maya Chen",
    role: "Packaging & Sustainability",
    company: "Wanaka Seafood",
    domain: "wanakaseafood.com",
    avatarSrc: "/avatars/maya.svg",
    avatarFallback: "MC",
  },
];

export const homeActivityFeed: ActivityFeedItem[] = [
  {
    id: "activity-1",
    type: "meeting",
    dayGroup: "Today",
    displayMode: "hero",
    title: "Logistics sync - Maersk starts in 24 min",
    insight: "ETA drift +6 days requires customer notification decision before noon.",
    owner: "Ops desk",
    time: "Today · 1:36 PM",
    priority: "High",
    source: "Meetings",
    sourceDomain: "teams.microsoft.com",
    linkedMeetingId: "meeting-2",
    ctaLabel: "Join now",
  },
  {
    id: "activity-2",
    type: "artifact",
    dayGroup: "Today",
    displayMode: "hero",
    title: "Agent artifact: pricing variance digest generated",
    insight: "Two suppliers outside threshold. Suggested mitigation ready for review.",
    owner: "Pricing monitor",
    time: "Today · 06:01 AM",
    priority: "Medium",
    source: "Agents",
    sourceDomain: "ubik.ai",
    ctaLabel: "Open artifact",
  },
  {
    id: "activity-3",
    type: "approval",
    dayGroup: "Today",
    displayMode: "row",
    title: "Approval required: detention clause response",
    insight: "Draft prepared with clause 4.2 preserved; legal sign-off needed now.",
    owner: "Sarah Kim",
    time: "Today · 08:42 AM",
    priority: "Critical",
    source: "Approvals",
    sourceDomain: "gmail.com",
    linkedThreadId: "thread-1",
    ctaLabel: "Review approval",
  },
  {
    id: "activity-4",
    type: "followup",
    dayGroup: "Yesterday",
    displayMode: "row",
    title: "Inbox follow-up: BL copy still pending",
    insight: "Supplier expects reminder before cargo release window closes.",
    owner: "Thai Union Ops",
    time: "Today · 10:07 AM",
    priority: "High",
    source: "Inbox",
    sourceDomain: "thaiunion.com",
    linkedThreadId: "thread-3",
    ctaLabel: "Open thread",
  },
];

export const homeUsageOverview: HomeUsageOverview = {
  stats: [
    {
      id: "usage-stat-1",
      label: "Revenue influenced",
      value: "$54.9K",
      detail: "Commercial value kept inside the active operating loop",
      trend: { direction: "up", label: "+12%", tone: "positive" },
    },
    {
      id: "usage-stat-2",
      label: "Working capital protected",
      value: "$18.2K",
      detail: "Cash release risk pulled back inside target payment terms",
      trend: { direction: "up", label: "+$4.6K", tone: "positive" },
    },
    {
      id: "usage-stat-3",
      label: "Operating margin defended",
      value: "+2.4 pts",
      detail: "Pricing exceptions resolved before quote discipline slipped",
      trend: { direction: "up", label: "+0.6 pts", tone: "positive" },
    },
    {
      id: "usage-stat-4",
      label: "Morning brief hit rate",
      value: "87%",
      detail: "Brief-linked actions cleared before noon",
      trend: { direction: "up", label: "+9 pts", tone: "positive" },
    },
    {
      id: "usage-stat-5",
      label: "Decisions shipped",
      value: "18",
      detail: "Approvals, escalations, and outbound moves completed",
      trend: { direction: "up", label: "+4", tone: "positive" },
    },
    {
      id: "usage-stat-6",
      label: "Hours returned",
      value: "31.4h",
      detail: "Operator capacity shifted out of trace work and into customer execution",
      trend: { direction: "up", label: "+6.2h", tone: "positive" },
    },
  ],
  activity: [
    { id: "activity-grid-1", level: 0, label: "Apr 1" },
    { id: "activity-grid-2", level: 1, label: "Apr 2" },
    { id: "activity-grid-3", level: 1, label: "Apr 3" },
    { id: "activity-grid-4", level: 0, label: "Apr 4" },
    { id: "activity-grid-5", level: 2, label: "Apr 5" },
    { id: "activity-grid-6", level: 2, label: "Apr 6" },
    { id: "activity-grid-7", level: 1, label: "Apr 7" },
    { id: "activity-grid-8", level: 0, label: "Apr 8" },
    { id: "activity-grid-9", level: 1, label: "Apr 9" },
    { id: "activity-grid-10", level: 2, label: "Apr 10" },
    { id: "activity-grid-11", level: 1, label: "Apr 11" },
    { id: "activity-grid-12", level: 0, label: "Apr 12" },
    { id: "activity-grid-13", level: 1, label: "Apr 13" },
    { id: "activity-grid-14", level: 2, label: "Apr 14" },
    { id: "activity-grid-15", level: 1, label: "Apr 15" },
    { id: "activity-grid-16", level: 0, label: "Apr 16" },
    { id: "activity-grid-17", level: 0, label: "Apr 17" },
    { id: "activity-grid-18", level: 1, label: "Apr 18" },
    { id: "activity-grid-19", level: 0, label: "Apr 19" },
    { id: "activity-grid-20", level: 0, label: "Apr 20" },
    { id: "activity-grid-21", level: 1, label: "Apr 21" },
    { id: "activity-grid-22", level: 2, label: "Apr 22" },
    { id: "activity-grid-23", level: 3, label: "Apr 23" },
    { id: "activity-grid-24", level: 2, label: "Apr 24" },
    { id: "activity-grid-25", level: 0, label: "Apr 25" },
    { id: "activity-grid-26", level: 1, label: "Apr 26" },
    { id: "activity-grid-27", level: 2, label: "Apr 27" },
    { id: "activity-grid-28", level: 3, label: "Apr 28" },
    { id: "activity-grid-29", level: 4, label: "Apr 29" },
    { id: "activity-grid-30", level: 3, label: "Apr 30" },
    { id: "activity-grid-31", level: 1, label: "May 1" },
    { id: "activity-grid-32", level: 2, label: "May 2" },
    { id: "activity-grid-33", level: 0, label: "May 3" },
    { id: "activity-grid-34", level: 1, label: "May 4" },
    { id: "activity-grid-35", level: 0, label: "May 5" },
    { id: "activity-grid-36", level: 2, label: "May 6" },
    { id: "activity-grid-37", level: 3, label: "May 7" },
    { id: "activity-grid-38", level: 4, label: "May 8" },
    { id: "activity-grid-39", level: 3, label: "May 9" },
    { id: "activity-grid-40", level: 2, label: "May 10" },
    { id: "activity-grid-41", level: 1, label: "May 11" },
    { id: "activity-grid-42", level: 2, label: "May 12" },
    { id: "activity-grid-43", level: 3, label: "May 13" },
    { id: "activity-grid-44", level: 4, label: "May 14" },
    { id: "activity-grid-45", level: 2, label: "May 15" },
    { id: "activity-grid-46", level: 1, label: "May 16" },
    { id: "activity-grid-47", level: 0, label: "May 17" },
    { id: "activity-grid-48", level: 1, label: "May 18" },
  ],
  footer:
    "UBIK is carrying more operating load without adding coordination drag: $54.9K of revenue, $18.2K of working capital, and 2.4 margin points stayed onside while 87% of brief-linked actions cleared before noon.",
};

export const activeOrders = [
  {
    id: "PO-2847",
    clientId: "atlantic-fresh",
    sku: "26/30 PD Tail",
    weight: "3.2 MT",
    status: "proforma-sent",
    value: 18240,
  },
  {
    id: "PO-2851",
    clientId: "atlantic-fresh",
    sku: "Atlantic Salmon Fillet",
    weight: "1.8 MT",
    status: "awaiting-bl",
    value: 14600,
  },
  {
    id: "PO-2839",
    clientId: "tastematic",
    sku: "Squid Rings IQF",
    weight: "5.0 MT",
    status: "in-transit",
    value: 22100,
  },
];

export const cargoMovements = [
  {
    containerId: "MSCU-4421099",
    clientId: "atlantic-fresh",
    destination: "Rotterdam",
    vessel: "MSC Eloise",
    etaDays: 16,
    etaDate: "Apr 28",
    lastEvent: "Departed Kochi",
    delayDays: 0,
  },
  {
    containerId: "MAEU-7712034",
    clientId: "atlantic-fresh",
    destination: "Seattle",
    vessel: "Maersk Nitra",
    etaDays: 21,
    etaDate: "May 3",
    lastEvent: "Transshipment at Colombo",
    delayDays: 6,
  },
  {
    containerId: "CMAU-8834122",
    clientId: "tastematic",
    destination: "New Jersey",
    vessel: "CMA CGM Titan",
    etaDays: 34,
    etaDate: "May 16",
    lastEvent: "Loaded at Shanghai",
    delayDays: 0,
  },
];

export const projects: ProjectRecord[] = [
  {
    id: "project-1",
    name: "Mumbai-Rotterdam Q2",
    code: "MR-Q2",
    status: "On track",
    owner: "Hemanth",
    progress: 68,
    summary: "Main shipping lane workstream covering rate confirmation, container release, and buyer updates.",
    milestones: [
      { label: "Contract revision approved", state: "Done" },
      { label: "Rate confirmation sent", state: "Active" },
      { label: "Cargo loaded", state: "Upcoming" },
    ],
    linked: [
      { label: "Sales PI to PO workflow", kind: "workflow" },
      { label: "Rate confirmation thread", kind: "chat" },
      { label: "Detention exception approval", kind: "approval" },
    ],
    team: ["Sarah Kim", "Raj Mehta", "Logistics Bot"],
    nextActions: ["Approve legal wording", "Confirm customer note", "Update project timeline"],
  },
  {
    id: "project-2",
    name: "Supplier Compliance Audit",
    code: "SCA-26",
    status: "At risk",
    owner: "Compliance",
    progress: 41,
    summary: "Audit workstream focused on supplier certificate freshness and exception handling.",
    milestones: [
      { label: "Document collection", state: "Active" },
      { label: "Risk review", state: "Upcoming" },
      { label: "Audit closure", state: "Upcoming" },
    ],
    linked: [
      { label: "Thai Union exception", kind: "approval" },
      { label: "Policy watch brief", kind: "report" },
      { label: "Supplier review sync", kind: "meeting" },
    ],
    team: ["Raj Mehta", "Compliance Bot"],
    nextActions: ["Confirm extension window", "Validate new uploads", "Decide PO release posture"],
  },
  {
    id: "project-3",
    name: "Atlantic Fresh Q3",
    code: "AF-Q3",
    status: "Needs attention",
    owner: "Finance",
    progress: 84,
    summary: "Margin-sensitive lane where pricing watch signals have started trending below threshold.",
    milestones: [
      { label: "Inventory allocation", state: "Done" },
      { label: "Margin review", state: "Active" },
      { label: "Commercial approval", state: "Upcoming" },
    ],
    linked: [
      { label: "Daily pricing workflow", kind: "workflow" },
      { label: "Pricing anomaly brief", kind: "report" },
    ],
    team: ["Finance Agent", "Sales ops"],
    nextActions: ["Review pricing brief", "Decide escalation path"],
  },
];

export const approvals: ApprovalItem[] = [
  {
    id: "approval-1",
    title: "Approve rate confirmation reply",
    workflow: "Sales PI to PO",
    status: "Urgent",
    confidence: 94,
    recommendation: "Approve the reply draft with the detention clause preserved and send today.",
    inputSummary: "The system aligned the latest forwarder reply, contract revision, and prior negotiation thread.",
    provenance: [
      "Email thread with Sarah Kim",
      "Contract MR-Q2 rev 3",
      "Legal note from March 28",
    ],
    actions: ["Approve and send", "Edit response", "Reject recommendation"],
  },
  {
    id: "approval-2",
    title: "Supplier extension exception",
    workflow: "Compliance monitoring",
    status: "Urgent",
    confidence: 89,
    recommendation: "Allow the extension but keep PO release behind manual review until the HACCP files are verified.",
    inputSummary: "The system traced the request to the supplier audit, PO timing, and prior exceptions for the same vendor.",
    provenance: [
      "WhatsApp note from Thai Union Ops",
      "Supplier Compliance Audit project",
      "Policy watch brief on document freshness",
    ],
    actions: ["Approve exception", "Hold PO", "Request more context"],
  },
  {
    id: "approval-3",
    title: "Publish pricing anomaly digest",
    workflow: "Daily pricing workflow",
    status: "Review",
    confidence: 82,
    recommendation: "Share the digest internally only and wait one more run before alerting customers.",
    inputSummary: "Two margin anomalies were detected, but both are within the temporary variance threshold.",
    provenance: ["Workflow run 842", "ERP landed costs", "Supplier feed delta"],
    actions: ["Share internally", "Escalate externally", "Dismiss"],
  },
];

export const workflowDefinitions: WorkflowDefinition[] = [
  {
    id: "wf-1",
    name: "Sales PI to PO",
    owner: "Commercial ops",
    cadence: "Manual trigger",
    approvalMode: "Required",
    outcomes: "Turns customer threads into approved outbound responses and internal tasks.",
  },
  {
    id: "wf-2",
    name: "Daily pricing workflow",
    owner: "Pricing",
    cadence: "Daily · 06:00 UTC",
    approvalMode: "Only on anomalies",
    outcomes: "Assembles landed cost changes and produces a margin watch brief.",
  },
  {
    id: "wf-3",
    name: "Compliance monitoring",
    owner: "Compliance",
    cadence: "Hourly watch",
    approvalMode: "Required",
    outcomes: "Monitors certificate freshness and routes supplier exceptions into review.",
  },
];

export const workflowRuns: WorkflowRun[] = [
  {
    id: "run-1",
    name: "Sales PI to PO · MR-Q2",
    status: "Awaiting approval",
    startedAt: "Today · 08:39",
    owner: "Commercial ops",
    summary: "Context assembled from inbound email, contract, and prior thread. Draft reply is ready for human review.",
    steps: [
      { id: "step-1", label: "Assemble thread context", status: "done" },
      { id: "step-2", label: "Extract tasks and policy checks", status: "done" },
      { id: "step-3", label: "Generate reply draft", status: "done" },
      { id: "step-4", label: "Await approval", status: "running" },
    ],
    artifacts: ["Draft response", "Context packet", "Approval note"],
  },
  {
    id: "run-2",
    name: "Daily pricing workflow · Atlantic Fresh",
    status: "Completed",
    startedAt: "Today · 06:00",
    owner: "Pricing",
    summary: "Completed with two margin anomalies and a new internal digest.",
    steps: [
      { id: "step-5", label: "Pull supplier feeds", status: "done" },
      { id: "step-6", label: "Calculate margin shifts", status: "done" },
      { id: "step-7", label: "Write daily brief", status: "done" },
    ],
    artifacts: ["Pricing digest", "Anomaly trace"],
  },
];

export const agents: AgentRecord[] = [
  {
    id: "agent-1",
    name: "Inbox triage agent",
    status: "Healthy",
    lastRun: "2 min ago",
    linkedWorkflow: "Sales PI to PO",
    summary: "Prioritizes inbound threads and assembles source context before the operator opens them.",
  },
  {
    id: "agent-2",
    name: "Pricing monitor agent",
    status: "Watching",
    lastRun: "12 min ago",
    linkedWorkflow: "Daily pricing workflow",
    summary: "Monitors supplier price movement and flags anomalies before customer impact.",
  },
  {
    id: "agent-3",
    name: "Compliance review agent",
    status: "Paused",
    lastRun: "Yesterday",
    linkedWorkflow: "Compliance monitoring",
    summary: "Tracks certificate freshness and prepares exception packets for human review.",
  },
];

export const intelligenceRecords: IntelligenceRecord[] = [
  {
    id: "intel-1",
    title: "EU cold-chain policy watch",
    freshness: "Updated 42 min ago",
    source: "Policy monitor",
    summary: "No new restrictions, but two wording changes affect inspection lead times for reefers.",
  },
  {
    id: "intel-2",
    title: "Atlantic lane pricing brief",
    freshness: "Updated 2 hrs ago",
    source: "Pricing monitor",
    summary: "Margin pressure concentrated in frozen whitefish lots; two suppliers remain outside threshold.",
  },
  {
    id: "intel-3",
    title: "Competitor watch digest",
    freshness: "Yesterday",
    source: "Research agent",
    summary: "Two competing distributors widened payment terms this week; monitor implications for renewal offers.",
  },
];

export const archiveRecords: ArchiveRecord[] = [
  { id: "archive-1", title: "March operator brief", type: "Brief", updatedAt: "Mar 29", owner: "Ubik" },
  { id: "archive-2", title: "Supplier audit closure pack", type: "Project", updatedAt: "Mar 27", owner: "Compliance" },
  { id: "archive-3", title: "Pricing monitor run 801", type: "Workflow run", updatedAt: "Mar 25", owner: "Pricing" },
];

export const settingsSections: SettingsSection[] = [
  {
    id: "settings-1",
    title: "Workspace",
    description: "Operator defaults for tabs, theme, and shell behavior.",
    values: [
      { label: "Default home", value: "Chat" },
      { label: "Theme", value: "Paper-first light" },
      { label: "Workbench restore", value: "Session only" },
    ],
  },
  {
    id: "settings-2",
    title: "Connectors",
    description: "Connected systems available in the current operator workspace.",
    values: [
      { label: "Messaging", value: "Gmail, Slack, WhatsApp" },
      { label: "Systems", value: "ERP, CRM, Drive" },
      { label: "Calendar", value: "Connected" },
    ],
  },
  {
    id: "settings-3",
    title: "Environment",
    description: "Runtime metadata and deployment visibility.",
    values: [
      { label: "Workspace", value: "Business / Prod" },
      { label: "Version", value: "v1.0.4" },
      { label: "Mode", value: "Desktop + Web" },
    ],
  },
];

export const helpResources: HelpResource[] = [
  {
    id: "help-1",
    title: "Inbox to approval flow",
    description: "How Ubik assembles thread context, extracts tasks, and routes items into review.",
    action: "Open guide",
  },
  {
    id: "help-2",
    title: "Workflow trace inspection",
    description: "How to read runtime artifacts, provenance, and execution steps.",
    action: "Read docs",
  },
  {
    id: "help-3",
    title: "Operator support",
    description: "Escalation paths, release notes, and implementation caveats.",
    action: "Contact support",
  },
];

function getUnifiedTaskPriorityWeight(priority: UnifiedTask["priority"]) {
  if (priority === "Urgent") return 4;
  if (priority === "High") return 3;
  if (priority === "Medium") return 2;
  return 1;
}

function getUnifiedTaskSection(task: UnifiedTask): number {
  return task.section === "Today" ? 0 : 1;
}

function buildTaskTimeline(dayOffset: number, startHour: number, durationHours: number) {
  const start = new Date(2026, 3, 17 + dayOffset, startHour, 0, 0, 0);
  const end = new Date(start);
  end.setHours(end.getHours() + durationHours);

  return {
    timelineStart: start.toISOString(),
    timelineEnd: end.toISOString(),
  };
}

export const unifiedTasks: UnifiedTask[] = [
  ...meetings.flatMap((meeting, index) =>
    meeting.actionItems.map((action, actionIndex) => ({
      id: `meeting-task-${meeting.id}-${actionIndex}`,
      title: action,
      summary: `${meeting.title} still needs an explicit operator follow-through.`,
      project: meeting.title,
      owner: meeting.owner,
      priority: meeting.stage === "Upcoming" ? "High" : "Medium",
      source: "meetings" as const,
      sourceLabel: "Meeting brief",
      href: `/tasks?task=meeting-task-${meeting.id}-${actionIndex}`,
      originHref: `/meetings/${meeting.id}`,
      section: meeting.stage === "Upcoming" && index < 2 ? "Today" : "No deadline",
      dueLabel: meeting.time,
      category: "Meeting carry-forward",
      ...buildTaskTimeline(index, 9 + actionIndex * 2, 4),
    })),
  ),
  ...approvals.map((approval, index) => ({
    id: `approval-task-${approval.id}`,
    title: approval.title,
    summary: approval.recommendation,
    project: approval.workflow,
    owner: "Approval queue",
    priority: approval.status === "Urgent" ? "Urgent" : "High",
    source: "approvals" as const,
    sourceLabel: "Approval packet",
    href: `/tasks?task=approval-task-${approval.id}`,
    originHref: "/approvals",
    section: index < 3 ? "Today" : "No deadline",
    dueLabel: approval.status,
    category: "Approval gating",
    ...buildTaskTimeline(index === 0 ? 0 : index - 1, 11 + index, 6),
  })),
  ...inboxThreads
    .filter(
      (thread) =>
        thread.priorityBand === "needs_attention" ||
        thread.priorityBand === "waiting_on_you" ||
        thread.followUpStatus === "blocked_by_approval" ||
        thread.followUpStatus === "due_soon" ||
        thread.priority === "Critical",
    )
    .map((thread, index) => ({
      id: `inbox-task-${thread.id}`,
      title: thread.linkedTask?.label ?? thread.taskPacket.taskTitle ?? thread.extractedTasks[0] ?? thread.subject,
      summary: thread.preview,
      project: thread.project,
      owner: thread.sender,
      priority: thread.priority === "Critical" ? "Urgent" : thread.priority,
      source: "inbox" as const,
      sourceLabel: thread.source === "Email" ? "Inbox / Gmail" : thread.source === "Slack" ? "Inbox / Slack" : "Inbox",
      href: `/tasks?task=inbox-task-${thread.id}`,
      originHref: `/inbox/${thread.id}`,
      section:
        thread.priority === "Critical" || thread.followUpStatus === "due_soon" || index < 2 ? "Today" : "No deadline",
      dueLabel: thread.dueRisk,
      category: "Follow-up",
      ...buildTaskTimeline(index, 10 + (index % 3) * 2, 3),
    })),
  ...workflowRuns
    .filter((run) => run.status !== "Completed")
    .map((run, index) => ({
      id: `workflow-task-${run.id}`,
      title: run.name,
      summary: run.summary,
      project: run.owner,
      owner: run.owner,
      priority: run.status === "Awaiting approval" ? "High" : "Low",
      source: "workflows" as const,
      sourceLabel: "Workflow run",
      href: `/tasks?task=workflow-task-${run.id}`,
      originHref: "/workflows",
      section: run.status === "Awaiting approval" || index === 0 ? "Today" : "No deadline",
      dueLabel: run.startedAt,
      category: "Automation follow-through",
      ...buildTaskTimeline(index + 1, 8 + index, 8),
    })),
]
  .sort((left, right) => {
    if (getUnifiedTaskSection(left) !== getUnifiedTaskSection(right)) {
      return getUnifiedTaskSection(left) - getUnifiedTaskSection(right);
    }
    return getUnifiedTaskPriorityWeight(right.priority) - getUnifiedTaskPriorityWeight(left.priority);
  })
  .slice(0, 12);

export function getRouteMeta(pathname: string) {
  const exactMatch = routeMetas.find((route) => route.path === pathname);
  if (exactMatch) return exactMatch;

  const nestedMatch = routeMetas.find((route) => route.path !== "/" && pathname.startsWith(`${route.path}/`));
  if (nestedMatch) return nestedMatch;

  return routeMetas.find((route) => route.path === "/");
}
